#!/bin/sh

file=$(du -a ~/documents/library | grep -i "\.pdf$" | cut -f2- | rev | cut -d. -f2- | rev | awk -F'/' '{print $NF}' | fzf --border --margin 20%)
path=$(find ~/documents/library -type f -name "$file".pdf)

if [ -e "$path" ]; then
	okular "$path" &
else
	exit
fi