#!/bin/sh

# file=$(du -a ~/documents/library | grep -i "\.pdf$" | cut -f2- | rev | cut -d. -f2- | rev | awk -F'/' '{print $NF}' | fzf --border --margin 20%)
# path=$(find ~/documents/library -type f -name "$file".pdf)

# if [ -e "$path" ]; then
# 	okular "$path" &
# else
# 	exit
# fi
desktop_file() {
  find ~/documents/library -type f -name "*.pdf" 2>/dev/null 
}

selected="$(desktop_file | sed 's/.desktop//g' | sort | fzf -e -i -m --reverse --delimiter / --with-nth -1)"
[ -z "$selected" ] && exit
cd || return
# setsid okular "$selected" ; done
 while read -r line ; do setsid okular "$selected"  ; done