#!/bin/sh
shopt -s expand_aliases

selected="$(compgen -c | xprompt -c -i -s -G C -g 400x50+0-150) pdf" 
source ~/.config/zsh/aliases.sh
[ -z "$selected" ] && exit
if [ "$selected" == "firefox" ]; then
	firefox >/dev/null 2>&1 &
if [ "$selected" == "firefox" ]; then
else
	"$selected" >/dev/null 2>&1 &
fi

