#!/bin/sh
# shopt -s expand_aliases

# selected="$(compgen -c | xprompt -c -i -s -G C -g 400x50+0-150) pdf" 
# source ~/.config/zsh/aliases.sh
# [ -z "$selected" ] && exit
# if [ "$selected" == "firefox" ]; then
# 	firefox >/dev/null 2>&1 &
# if [ "$selected" == "firefox" ]; then
# else
# 	"$selected" >/dev/null 2>&1 &
# fi

#!/bin/sh
shopt -s expand_aliases

# get the list of all my packages
command_list="$(nix-store -q --references /var/run/current-system/sw | cut -d'-' -f2- |  cut -d '-' -f 1)"
# append new options
command_list+="
book
exec
locate
"

# Use xprompt with the modified command list
selected="$(echo "$command_list" | xprompt -c -i -s -G C -g 400x50+0-150)"

source ~/.config/zsh/aliases.sh
[ -z "$selected" ] && exit

if [ "$selected" == "firefox" ]; then
    firefox >/dev/null 2>&1 &
if [ "$selected" == "book" ]; then
    sh book.sh

else
    "$selected" >/dev/null 2>&1 &
fi
