#!/bin/sh# fuzzy_cmd filters a command via fzf and launches it with lnch
# use it together with fuzzy_win like this: fuzzy_win fuzzy_cmd
selected="$(compgen -c | fzf -e -i -m --reverse --delimiter / --with-nth -3,-2,-1 )"
[ -z "$selected" ] && exit
cd || return
echo "$selected" | while read -r line ; do setsid xargs lnch ; done #setsid xdg-open "$line".desktop ; done
